### ISSUE TITLE
Version of elastin/beats? 

### ISSUE THREAD

**Issue by gshamov** [hpcugent/moabbeat#1]
Hi,

I have tried to build it against current libbeat; but I get the following error:

go build
# github.com/hpcugent/moabbeat/beater
../../../src/github.com/hpcugent/moabbeat/beater/moabbeat.go:18: undefined: "github.com/hpcugent/moabbeat/vendor/github.com/elastic/beats/libbeat/publisher".Client
make: *** [moabbeat] Error 2 

Does moabbeat require any specific libbeat version?

**Comment by gshamov** [comment]
I have tried the build using Golang 1.8.3 and elastic/beat-5.3.3 .

**Comment by gshamov** [comment]
I have then tried using Golang 1.7.6 against the current beats (5.6). 

../src/github.com/hpcugent/moabbeat/beater/moabbeat.go:18: undefined: publisher.Client .
Beats ecosystem seems kind of fragile.
